### ISSUE TITLE
Practica 2_DISEÑO DE OBJETOS EN 3D

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo_prestadores-de-servicios#2]
[Practica 2_DISEÑO DE OBJETOS EN 3D.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo_prestadores-de-servicios/files/8240700/Practica.2_DISENO.DE.OBJETOS.EN.3D.pdf)

**Comment by dulce-blm** [comment]
Calificación 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
